module.exports.NO_EMAIL = 'Please provide email.'
module.exports.NO_PASSWORD = 'Please provide password.'
module.exports.NOT_FOUND = 'User does not exist.'
module.exports.WRONG_PASSWORD = 'Wrong password.'
module.exports.USER_EXISTS = 'User already exists.'
